#!/usr/bin/perl
use strict;
use IPC::Run qw(start run);

mkdir("fifos");
system("mkfifo fifos/fuse-to-daemon fifos/daemon-to-fuse fifos/daemon-to-notify fifos/daemon-to-lowerer");

mkdir("data");
mkdir("data/lower");
mkdir("data/upper");
mkdir("data/work");
mkdir("merge");
mkdir("mount");
mkdir("c00git");
system("echo > syncfs-pings");

my @ps;
my @fs;
my $path = shift;
my $arch = `uname -m`;
chomp $arch;

my $localn = ($remote eq "10.4.0.1") ? "10.4.0.2" : "10.4.0.1";
system("cd data/upper; git init; git config user.name 'SyncFS'; git config user.email 'pipcet\@gmail.com'; git config pull.rebase false; git remote add $remote $remote:sync/data/upper");

run(["sudo", "mount", "-toverlay", "-olowerdir=data/lower,upperdir=data/upper,workdir=data/work,rw", "overlay", "merge"]) or die;
push @fs, "merge";
push @ps, start(["$path/$arch/c00gitfs", "data/upper", "merge", "c00git"]);
push @fs, "c00git";
sleep 1;
my $remote = shift;
# not currently used.
push @ps, start(["$path/$arch/syncfs", "merge", "merge", "mount", "fifos"]);
push @fs, "mount";
sleep 1;
push @ps, start(["perl", "$path/syncfs.pl", "fifos"]);
sleep 1;
push @ps, start(["perl", "$path/syncfs-notifier.pl", "fifos", $remote]);
sleep 1;
push @ps, start(["perl", "$path/syncfs-secondary.pl", $remote]);
sleep 1;
push @ps, start(["perl", "$path/syncfs-lowerer.pl", $localn, $remote]);
sleep 1;
# disabled; overlayfs is buggy
# push @ps, start(["perl", "$path/syncfs-colowerer.pl", $localn, $remote]);
sleep 1;

sub terminate {
    for my $p (@ps) {
	$p->kill_kill;
    }
    while (@fs) {
	my $fs = shift @fs;
	my $stdin = "";
	my $stdout = "";
	my $stderr = "";
	run(["sudo", "umount", $fs], \$stdin, \$stdout, \$stderr);
	if ($stderr =~ /not mounted/) {
	} else {
	    warn $stdout if $stdout ne "";
	    warn $stderr if $stderr ne "";
	    push @fs, $fs;
	    sleep 1;
	}
    }
    warn "All file systems unmounted. Terminating.";
    exit 0;
}

$SIG{INT} = sub {
    terminate;
};

$SIG{TERM} = sub {
    terminate;
};

while (1) {
    sleep 1;
}
